### ISSUE TITLE
Variables a, b, and temp should be declared as local

### ISSUE THREAD

**Issue by drdholu** [aapatil2004/ASSIGNMENT_8_SE#1]
The variables a, b, and temp in the fibonacci function should be declared as local to avoid potential conflicts with other parts of the script or environment variables. This ensures that their scope is limited to the function.

**Comment by aapatil2004** [comment]
The issue has been resolved by declaring the variables `a`, `b`, and `temp` as local in the `fibonacci` function.

- **Branch**: `fix-local-variables-fibonacci`
- PR Reference: [#4](https://github.com/aapatil2004/ASSIGNMET_8_SE/pull/4)

The changes have been merged into the main branch. Please verify if everything is working as expected.
